### ISSUE TITLE
[Feature Request] Mustache Template iteration for List/Map

### ISSUE THREAD

**Issue by JustinVenus** [wickman/pystachio#28]
Would be nice to support iteration as documented in https://mustache.github.io/mustache.5.html

use case.

```yaml
NAMERD_TEMPLATE = """---
admin:
  port: {{thermos.ports[admin]}}
storage:
  kind: io.l5d.zk
    experimental: true
    pathPrefix: /dtabs/{{profile.environment}}
  zkAddrs:
{{#region.zk}}
  - host: {{host}}
    port: {{port}}
{{/region.zk}}
```

Where region is:
```python
class Region(Struct):
  zk            = Required(List(Map(String, String)))

Region(
    cluster='ZeroZero',
    zk = [
        {'host': 'zoo01', 'port': '2181'},
        {'host': 'zoo02', 'port': '2181'},
        {'host': 'zoo03', 'port': '2181'},
    ]
)
```

current result is:
```sh
aurora job create ZeroZero/nobody/devel/namerd namerd.aurora
Error loading configuration: #region.zk
```
